version: "3.7"
services:
  app:
    image: ghcr.io/${GITHUB_ACTOR}/gtp-fastapi-deploy-server:latest
    container_name: fastapi
    ports:
      - 33333:33333
    networks:
      - app

networks:
  app:
    driver: bridge