version: "3.12"
services:
  app:
    image: ghcr.io/younghyen7956/gtp-fastapi-deploy-server:latest
    container_name: fastapi
    ports:
      - 33333:33333
    networks:
      - app

networks:
  app:
    driver: bridge